name: configure_ansible_control_node

trigger:
- none

parameters:
- name: environment
  displayName: 'Host name'
  type: string
  default: "tmp-ubuntu.acn" 

stages:
- stage:
  displayName: 'Configure control node'
  pool:
    name: Default
  jobs:
  - deployment: configure_vm
    displayName: 'configure vm'
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            displayName: 'check if python is installed'
            inputs:
              targetType: 'inline'
              script: |
                python3 -m pip -V
            condition: always()
          - task: Bash@3
            displayName: 'install pip'
            inputs:
              targetType: 'inline'
              script: |
                curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
                python3 get-pip.py --user
            condition: failed()
          - task: Bash@3
            displayName: 'check if ansible is installed'
            inputs:
              targetType: 'inline'
              script: |
                ansible --version
            condition: always()
          - task: Bash@3
            displayName: 'install ansible'
            inputs:
              targetType: 'inline'
              script: |
                echo $USER_PWD > /tmp/file
                echo $ANSIBLE_PWD > /tmp/fileA
                cat /tmp/file | sudo -S groupadd azure
                cat /tmp/file | sudo -S usermod -a -G azure $(whoami)
                echo "Adding ansible user"
                cat /tmp/file | sudo -S useradd -m -p "$ANSIBLE_PWD" -s /bin/bash ansible
                echo "Adding ansible user to admins and azure group"
                cat /tmp/file | sudo -S usermod -aG sudo ansible
                cat /tmp/file | sudo -S usermod -a -G azure ansible
                cat /tmp/file | sudo -S -u ansible ssh-keygen -q -f /home/ansible/.ssh/id_rsa
                cat /tmp/file | sudo -S -u ansible chmod g+r /home/ansible/.ssh/
                cat /tmp/file | sudo -S -u ansible chmod 640 /home/ansible/.ssh/id_rsa.pub
                echo "Install ansible"
                cat /tmp/file | sudo -S -u ansible cat /tmp/fileA | sudo -S apt -y update
                cat /tmp/file | sudo -S -u ansible cat /tmp/fileA | sudo -S apt -y install ansible
                rm /tmp/file /tmp/fileA
                ansible --version
            env:
              ANSIBLE_PWD: $(ansible_pwd)
              USER_PWD: $(user_pwd)
            condition: failed()
          - task: Bash@3
            displayName: 'cat public ssh key'
            inputs:
              targetType: 'inline'
              script: |
                cat /home/ansible/.ssh/id_rsa.pub
            condition: always()
