name: configure_ansible_control_node

trigger:
- none

parameters:
- name: environment
  displayName: 'Host name'
  type: string
  default: "tmp-ubuntu.acn" 

stages:
- stage:
  displayName: 'Configure control node'
  pool:
    name: Default
  jobs:
  - deployment: configure_vm
    displayName: 'configure vm'
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            displayName: 'check if python is installed'
            inputs:
              targetType: 'inline'
              script: |
                python3 -m pip -V
          - task: Bash@3
            displayName: 'install pip'
            inputs:
              targetType: 'inline'
              script: |
                curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
                python3 get-pip.py --user
            condition: failed()
          - task: Bash@3
            displayName: 'check if ansible is installed'
            inputs:
              targetType: 'inline'
              script: |
                ansible --version
          - task: Bash@3
            displayName: 'install ansible'
            inputs:
              targetType: 'inline'
              script: |
                echo $USER_PWD > /tmp/file
                echo $ANSIBLE_PWD > /tmp/file2
                chmod 660 /tmp/file
                chmod 660 /tmp/file2
                echo "Adding ansible user"
                cat /tmp/file | sudo -S useradd -m -p "$ANSIBLE_PWD" -s /bin/bash ansible
                echo "Adding ansible user to admins"
                cat /tmp/file | sudo -S usermod -aG sudo ansible
                whoami
                cat /tmp/file2 | su - ansible
                whoami
                # ssh-keygen -q
                # cat /tmp/file2 | sudo -S apt update
                # cat /tmp/file2 | sudo -S apt install ansible
                # ansible --version
                rm /tmp/file /tmp/file2
            env:
              ANSIBLE_PWD: $(ansible_pwd)
              USER_PWD: $(user_pwd)
            condition: failed()
          - task: Bash@3
            displayName: 'cat public ssh key'
            inputs:
              targetType: 'inline'
              script: |
                cat ~/.ssh/id_rsa.pub
