#Pipeline for pushing ansible central node public key to ansible host (parameter)
name: connect_host_to_acn

#Artifacts from the pipeline resource get downloaded to $(PIPELINE.WORKSPACE)/acnconfig/publickey folder.
resources:
  pipelines:
  - pipeline: acnconfig
    source: configure_acn

trigger:
- none

parameters:
- name: host
  displayName: 'Ansible host name'
  type: string
  default: "tmp-ubuntu.localdeploymenthost" 

stages:
- stage: build
  pool:
    name: Default
  jobs:
  - job: build
    steps:
    - download: acnconfig
      displayName: 'download artifact'
      artifact: publickey
    - script: ls -al $(PIPELINE.WORKSPACE)/acnconfig/publickey
      displayName: 'show artifact content'
    - task: Bash@3
      displayName: 'cat public ssh key'
      inputs:
        targetType: 'inline'
        script: |
          file=$(ls -d $(PIPELINE.WORKSPACE)/acnconfig/publickey/*)
          pubkey=$(cat $file)
          echo "##vso[task.setvariable variable=pubkey;isOutput=true]${pubkey}"
      name: pubKeyVar
- stage: deploykey
  displayName: 'connect ansible host to ansible central node'
  pool:
    name: Default
  jobs:
  - deployment: pushKey
    variables:
      - name: acnpubkey
        value: $[ stageDependencies.build.build.outputs['pubKeyVar.pubkey'] ]
    displayName: 'save public key on host'
    environment: ${{ parameters.host }}
    strategy:
      runOnce:
        deploy:
          steps: 
          - download: none
          - script: set
            displayName: 'Show variables'
          - task: Bash@3
            displayName: 'cat public ssh key'
            inputs:
              targetType: 'inline'
              script: |
                echo $(acnpubkey)
          - task: Bash@3
            displayName: 'add ansible user'
            inputs:
              targetType: 'inline'
              script: |
                echo $USER_PWD > /tmp/file
                echo "Adding ansible user"
                cat /tmp/file | sudo -S useradd -m -s /sbin/nologin ansible
                echo "Adding ansible user to admins and admin to ansible group"
                cat /tmp/file | sudo -S usermod -aG sudo ansible
                cat /tmp/file | sudo -S echo "ansible ALL=(ALL) NOPASSWD: ALL" >>/etc/sudoers
                rm /tmp/file
            env:
              USER_PWD: $(user_pwd)
          - task: Bash@3
            displayName: 'add key to known_hosts'
            inputs:
              targetType: 'inline'
              script: |
                echo $USER_PWD > /tmp/file
                cat /tmp/file | sudo -S -u ansible mkdir ~/.ssh
                cat /tmp/file | sudo -S -u ansible touch ~/.ssh/authorized_keys
                cat /tmp/file | sudo -S -u ansible chmod -R go= ~/.ssh
                cat /tmp/file | sudo -S -u ansible echo $(acnpubkey) > ~/.ssh/authorized_keys
                cat /tmp/file | sudo -S -u ansible cat ~/.ssh/authorized_keys
            env:
              USER_PWD: $(user_pwd)
          - task: Bash@3
            displayName: 'show host ip address'
            inputs:
              targetType: 'inline'
              script: |
                hostname -I | awk '{print $1}'
