#Pipeline for pushing ansible central node public key to ansible host (parameter)
name: connect_host_to_acn

#Artifacts from the pipeline resource get downloaded to $(PIPELINE.WORKSPACE)/acnconfig/publickey folder.
resources:
  pipelines:
  - pipeline: acnconfig
    source: configure_acn

trigger:
- none

parameters:
- name: host
  displayName: 'Ansible host name'
  type: string
  default: "tmp-ubuntu.localdeploymenthost" 

stages:
- stage: build
  pool:
    name: Default
  jobs:
  - job: build
    steps:
    - download: acnconfig
      displayName: 'download artifact'
      artifact: publickey
    - script: ls -al $(PIPELINE.WORKSPACE)/acnconfig/publickey
      displayName: 'show artifact content'
    - task: Bash@3
      displayName: 'cat public ssh key'
      inputs:
        targetType: 'inline'
        script: |
          pubkey=$(ls -d $(PIPELINE.WORKSPACE)/acnconfig/publickey/* | cat )
          echo "##vso[task.setvariable variable=pubkey;isOutput=true]${pubkey}"
      name: pubKeyVar
- stage: deploykey
  displayName: 'connect ansible host to ansible central node'
  pool:
    name: Default
  jobs:
  - deployment: pushKey
    variables:
      - name: acnpubkey
        value: $[ stageDependencies.build.build.outputs['pubKeyVar.pubkey'] ]
    displayName: 'save public key on host'
    environment: ${{ parameters.host }}
    strategy:
      runOnce:
        deploy:
          steps: 
          - script: set
            displayName: 'Show variables'
          - task: Bash@3
            displayName: 'cat public ssh key'
            inputs:
              targetType: 'inline'
              script: |
                echo $(acnpubkey)
           
