name: connect_host_to_acn

trigger:
- none

parameters:
- name: acn
  displayName: 'Ansible central node name'
  type: string
  default: "tmp-ubuntu.acn" 
- name: host
  displayName: 'Ansible host name'
  type: string
  default: "tmp-ubuntu.localdeploymenthost" 

stages:
- stage: pullKeyStage
  displayName: 'Read acn public ssh key'
  pool:
    name: Default
  jobs:
  - deployment: pullKey
    displayName: 'pull public ssh key'
    environment: ${{ parameters.acn }}
    strategy:
      runOnce:
        deploy:
          steps: 
          - task: Bash@3
            displayName: 'cat public ssh key'
            inputs:
              targetType: 'inline'
              script: |
                pubkey=$(cat /home/ansible/.ssh/id_rsa.pub)
                echo "##vso[task.setvariable variable=pubkey;isOutput=true]${pubkey}"
            name: pubKeyVar
          - task: Bash@3
            displayName: 'show public ssh key'
            inputs:
              targetType: 'inline'
              script: |
                set | grep ssh
                echo $(pubKeyVar.pubkey)
- stage: connectHostStage
  displayName: 'Connect ansible host to ansible central node'
  dependsOn: pullKeyStage
  pool:
    name: Default
  jobs:
  - deployment: pushKey
    variables:
      acnpubkey: $[stageDependencies.pullKey.outputs['pubKeyVar.pubkey']]
    displayName: 'save public key on host'
    environment: ${{ parameters.host }}
    strategy:
      runOnce:
        deploy:
          steps: 
          - script: set
            displayName: 'Show variables'
          - task: Bash@3
            displayName: 'cat public ssh key'
            inputs:
              targetType: 'inline'
              script: |
                echo $(acnpubkey)
           
