name: compile_go

trigger:
- none

resources:
  repositories:
  - repository: aoc
    type: github
    endpoint: martamazurkiewicz
    name: martamazurkiewicz/AdventOfCode
    ref: main

parameters:
- name: aoctask
  displayName: 'AoC task'
  type: string
  default: "2022-01" 

stages:
- stage:
  displayName: 'Build'
  pool:
    vmImage: 'ubuntu-latest'
  jobs: 
  - job: build
    steps:
    - checkout: aoc
    - task: Bash@3
      displayName: 'Check pipeline contents'
      inputs:
        targetType: 'inline'
        script: |
          ls -al $(System.DefaultWorkingDirectory)
          echo "===================="
          ls -al $(System.DefaultWorkingDirectory)/${{ parameters.aoctask }}
    - task: GoTool@0
      inputs:
        version: '1.17.4'
    - task: Go@0
      inputs:
        command: 'get'
        arguments: '-d'
        workingDirectory: '$(System.DefaultWorkingDirectory)/${{ parameters.aoctask }}'
    - task: Go@0
      inputs:
        command: 'build'
        workingDirectory: '$(System.DefaultWorkingDirectory)/${{ parameters.aoctask }}'
    - task: Bash@3
      displayName: 'Check pipeline contents'
      inputs:
        targetType: 'inline'
        script: |
          ls -al $(System.DefaultWorkingDirectory)/${{ parameters.aoctask }}
    - task: Bash@3
      displayName: 'run task'
      inputs:
        targetType: 'inline'
        script: |
          #./main
